### ISSUE TITLE
Small positioning issue

### ISSUE THREAD

**Issue by bookercodes** [ammezie/html-chatbox#1]
On narrrow displays, this looks nice:

![image](https://user-images.githubusercontent.com/11927968/40874164-c94aaac4-6663-11e8-96c9-47f8b3332b51.png)

But on wider displays, the formatting is a tiny bit off:

![image](https://user-images.githubusercontent.com/11927968/40874155-b1ffeaa0-6663-11e8-8291-0931e8fcb40b.png)

Would you please look into it?

**Comment by ammezie** [comment]
Fixed.
